site_name: GiraKoo Home
site_url: https://girakoo.com/
theme:
  name: readthedocs
  font:
    code: "JetBrains Mono"
    language: zh
nav:
  - 首页: index.md
  - GiString项目: gi_string.md
  - GiJansson项目: gi_jansson.md
  - GiLayout项目: gi_layout.md
  - GiStrenchImage项目: gi_strench_image.md