site_name: Gira Koo
site_url: https://girakoo.com/
theme:
  name: readthedocs
  font:
    code: "JetBrains Mono"
    language: zh
nav:
  - Home: index.md
  - GiString: gi_string.md
  - GiJansson: gi_jansson.md
  - GiLayout: gi_layout.md
  - GiStrenchImage: gi_strench_image.md