site_name: GiraKoo的技术分享
site_url: https://girakoo.cn/
extra_javascript:
  - js/baidu.js
  - js/font.js
repo_url: https://gitee.com/girakoo
copyright: <a href="https://beian.miit.gov.cn/" target="_blank">辽ICP备2023001429号</a> Copyright &copy; 2022-2023 girakoo.cn
theme:
  name: material
  logo: img/logo_hd_bg.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.top
    - navigation.path
    - content.code.copy
    - toc.integrate
    - navigation.sections
plugins:
  - offline
  - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]+'
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
markdown_extensions: 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: On this page
      toc_depth: 2
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
nav:
  - 主页: index.md
  - GiString: gi_string.md
  - GiJansson: gi_jansson.md
  - GiLayout: gi_layout.md
  - GiStrenchImage: gi_strench_image.md
  - GiListener: gi_listener.md